---
fixtures:
  repositories:
    stdlib:
      ref: "v6.6.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "v7.7.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    mount_core:
      ref: "1.0.4"
      repo: "https://github.com/puppetlabs/puppetlabs-mount_core"
  symlinks:
    vision_gluster: '#{source_dir}'
